---
- name: Create scripts directory
  file:
    path: "{{ icinga2_scripts_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install notification dependencies
  apt:
    name: curl
  when: icinga2_needs_notification_scripts

- name: Install check dependencies
  apt:
    name:
      - bc
      - jq

- name: Copy common files
  copy:
    src: "{{ item }}"
    dest: "{{ icinga2_scripts_path }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - common.py
    - common.sh

- name: Copy check scripts dependencies
  copy:
    src: "{{ item }}"
    dest: "{{ icinga2_scripts_path }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - tinkerforge
  when: icinga2_needs_tinkerforge

- name: Copy check scripts
  copy:
    src: "check_{{ item }}"
    dest: "{{ icinga2_scripts_path }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - dns_recursion
    - dns_repl
    - dnssec
    - dsync
    - free
    - hddtemp
    - jenkins
    - kernel
    - rdp
    - redis
    - server_rack
    - services
    - tty
    - unifi
    - zfs
    - zfs_snapshot
    - zpool_scrub

- name: Copy notification scripts
  copy:
    src: "notify_{{ item }}"
    dest: "{{ icinga2_scripts_path }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - host_mattermost
    - host_msmtp
    - service_mattermost
    - service_msmtp
  when: icinga2_needs_notification_scripts
